config/routes.rb
Rails.application.routes.draw do
  get 'articles/compare'

  root 'articles#index'

  resources :articles do
    member do
      get :buy
      get :redo
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base

  validates_presence_of :status, :text

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :load_article, only: [:edit, :update, :destroy, :buy, :redo]


  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def compare
  end

  def edit
  end

  def redo
    @article.status = 1
    @article.save
    redirect_to :back
  end

  def buy
    @article.status = 0
    @article.save
    redirect_to :back
  end

  def create
    @article = Article.new(article_params.merge({status: 1}))
    if @article.save
      redirect_to articles_path
    else
      flash[:errors] = @article.errors.messages
      redirect_to :back
    end
  end

  def update
    if @article.update_attributes(article_params)
      redirect_to articles_path
    else
      flash[:errors] = @article.errors.messages
      redirect_to :back
    end
  end

   def destroy
    @article.destroy
    redirect_to :back
  end

   private

  def load_article
    @article = Article.find params[:id]
  end

  def article_params
    params.require(:article).permit(:text, :price, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  Name: <%= f.text_area :text %><br />
  Price: <%= f.text_field :price %><br />
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<h3> Edit Article </h3>
<%= render 'form' %>

<%= link_to '< Back', articles_path %>

app/views/articles/index.html.erb
<h1>Article:</h1>
  <ul>
    <% @articles.each do |article| %>

      <% if article.status == 1 %>
        <li>
          <%= article.text %>:
          <%= article.price %>
          <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-sm btn-primary' %>
          <%= link_to 'Delete', article_path(article), method: :delete, class: 'btn btn-sm btn-danger' %>
          <%= link_to 'Buy', buy_article_path(article), class: 'btn btn-sm btn-danger' %>
          <%= check_box :article, :commands %>
        </li>
      <% end %>
    <% end %>
  </ul>
<h1>Basket:</h1>
  <ul>
    <% @articles.each do |article|
      if article.status == 0 %>
        <li>
          <%= article.text %>:
          <%= article.price %>
          <%= link_to 'Cancel', redo_article_path(article), class: 'btn btn-sm btn-primary' %>
        </li>
      <% end %>
    <% end %>
  </ul>
  <p>Total:
    <%= @articles.where(status: 0).sum(:price) %>
  </p>
<%= link_to 'Add product', new_article_path %>
<%= link_to 'Compare', articles_compare_path %>

app/views/articles/new.html.erb
<h3> New Product </h3>
<%= render 'form' %>

<%= link_to '< Back', articles_new_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>